### ISSUE TITLE
[GORAY] Development of a configuration file

### ISSUE THREAD

**Issue by g10z3r** [4rchr4y/rayfile#1]
# Project Configuration Structure Development

This document outlines the development plan for the project configuration structure. The configuration file structure and the corresponding library to work with it are detailed below.

### Versioning
- Implement version control for the configuration file to manage different versions and updates efficiently.

### General Settings
- **Project Directory Path**: Define the path to the project directory.
- **Target Folder Path**: Specify the path to the folder that needs to be analyzed.
- **Ignore List**: A list of items (files, directories) to be ignored during parsing.

### Picker Configuration
- **Concurrency Settings**: Configure the usage of gorutines for performance optimization (parser, engine).
- **Logging Settings**: Setup logging preferences (mode, ...).
- **Picker Toggle**: Ability to enable or disable specific pickers.
- **Field Compression**: Implement field compression to optimize storage.

### Analyzer Settings
- Detailed configuration options for customizing the behavior of the analyzer.

### Features
- **Environment Variable Support**: The library should allow the use of environment variables within the configuration file.
- **No Panic Policy**: The library must be robust and handle errors gracefully without causing panic.
- **Documentation**: Comprehensive documentation for all features and configurations provided by the library.
- **Version Policy**: Correct work with different types of versions. A foundation for the future must be laid so that in the future we can easily implement support for new versions. 
- **Default Values**: If some configuration parameters are not specified, there must be a set of default parameters. (We will discuss in more detail what should be default and what should not as the task progresses)

## References
- `docker-compose.yml`
- `gitlab-ci.yml`
- GitHub Actions YML files

This structure and the accompanying library aim to provide a comprehensive, flexible, and user-friendly approach to configuring and managing project settings.

### Basic example of YAML file

```toml
[workspace]
version = "1.0.193"
root= "."
policies="./policy"
ignore-list=[".git", ".docker"]
go-arch="${GOARCH}"

[analysis]
KRAIL1001 = {level = "info", target= "./lambdas"}

[analysis.SE]
level = "critical"
targer = "./internal"

[performance]
```
